/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package advprog;

import java.util.ArrayDeque;
import java.util.ArrayList;

/**
 *
 * @author kris
 */
public class GameWindow extends javax.swing.JFrame {

    /**
     * Creates new form GameWindow
     */    
    private int rows = 51;
    private int cols = 226;
    private SnakeBody snake = new SnakeBody();
    
    public GameWindow() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        //displaySnake();
        //snake.moveRight();
        //displaySnake();
        
        String disp = "";
         for(int i = 0; i < 100; i++){
            for(int j = 0; j < 100; j++){
                disp+= "123456789";
            }
            
            disp+="\n";
        }    
        
        snakeArea.setText(disp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        snakeArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        snakeArea.setEditable(false);
        snakeArea.setColumns(20);
        snakeArea.setRows(5);
        jScrollPane1.setViewportView(snakeArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean containsBody(int x, int y){
        ArrayDeque <Point> body = snake.getBody();
        
        for(Point p : body){                        
            System.out.println(p.getX()+"," + p.getY());            
            if(p.getX() == x && p.getY() == y)
                return true;
        }
        return false;
    }
    /*
    public void displaySnake(){
        StringBuilder display = new StringBuilder();
        
        int row = 50;
        int col = 226;
        
        for(int i = 0; i < row; i++){
            for(int j = 0; j < col; j++){
                if(containsBody(j,i)){
                    display.append("X");
                }else{
                    display.append(" ");
                }
            }
        
        }
            
        //get current end and add         
    }
    */
    
    public void displaySnake(){
        StringBuilder display = new StringBuilder();
        
        int row = 50;
        int col = 226;
        
        String disp = "";
         for(int i = 0; i < 100; i++){
            for(int j = 0; j < 100; j++){
                disp+= "123456789";
            }
            
            disp+="\n";
        }    
        
        snakeArea.setText(disp);
            
        //get current end and add         
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea snakeArea;
    // End of variables declaration//GEN-END:variables
}
